config setup
	charondebug="ike 2, knl 2, cfg 2"

conn gre30
	left=172.16.1.2
	leftid=172.16.1.2
	right=172.16.2.2
	rightid=172.16.2.2
	auto=start
	authby=psk
	keyexchange=ikev2
	ike=aes256-sha256-modp2048!
	esp=aes256-sha256!
	type=tunnel
	leftfirewall=yes
	rightfirewall=yes
