services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
